In [1]:
import numpy as np
import pandas as pd

In [2]:
delanay = pd.read_csv('/Data/temuge/cov19/drugdevelopment_pp/molecular_admet/data/raw/delaney.csv')
delanay

,Compound ID,ESOL predicted log solubility in mols per litre,Minimum Degree,Molecular Weight,Number of H-Bond Donors,Number of Rings,Number of Rotatable Bonds,Polar Surface Area,measured log solubility in mols per litre,smiles
0,Amigdalin,-0.974,1,457.432,7,3,7,202.32,-0.770,OCC3OC(OCC2OC(OC(C#N)c1ccccc1)C(O)C(O)C2O)C(O)...
1,Fenfuram,-2.885,1,201.225,1,2,2,42.24,-3.300,Cc1occc1C(=O)Nc2ccccc2
2,citral,-2.579,1,152.237,0,0,4,17.07,-2.060,CC(C)=CCCC(C)=CC(=O)
3,Picene,-6.618,2,278.354,0,5,0,0.00,-7.870,c1ccc2c(c1)ccc3c2ccc4c5ccccc5ccc43
4,Thiophene,-2.232,2,84.143,0,1,0,0.00,-1.330,c1ccsc1
...,...,...,...,...,...,...,...,...,...,...
1123,halothane,-2.608,1,197.381,0,0,0,0.00,-1.710,FC(F)(F)C(Cl)Br
1124,Oxamyl,-0.908,1,219.266,1,0,1,71.00,0.106,CNC(=O)ON=C(SC)C(=O)N(C)C
1125,Thiometon,-3.323,1,246.359,0,0,7,18.46,-3.091,CCSCCSP(=S)(OC)OC
1126,2-Methylbutane,-2.245,1,72.151,0,0,1,0.00,-3.180,CCC(C)C
1127,Stirofos,-4.320,1,365.964,0,1,5,44.76,-4.522,COP(=O)(OC)OC(=CCl)c1cc(Cl)c(Cl)cc1Cl

In [3]:
delanay['Compound ID'].nunique()

1128

In [4]:
duplicate_str = pd.read_csv('/Data/temuge/cov19/drugdevelopment_pp/molecular_admet/reports/duplicate_structures.csv')
duplicate_str

,compound_id,smiles,canonical_smiles,measured_logS
0,Amobarbital,CCC1(CCC(C)C)C(=O)NC(=O)NC1=O,CCC1(CCC(C)C)C(=O)NC(=O)NC1=O,-2.468
1,eucalyptol,CC12CCC(CC1)C(C)(C)O2,CC12CCC(CC1)C(C)(C)O2,-1.640
2,2-bromonaphthalene,c1c(Br)ccc2ccccc12,Brc1ccc2ccccc2c1,-4.400
3,Epiandrosterone,CC34CCC1C(CCC2CC(O)CCC12C)C3CCC4=O,CC12CCC3C(CCC4CC(O)CCC43C)C1CCC2=O,-4.160
4,mannitol,OCC(O)C(O)C(O)C(O)CO,OCC(O)C(O)C(O)C(O)CO,0.060
5,Dialifor,CCOP(=S)(OCC)SC(CCl)N1C(=O)c2ccccc2C1=O,CCOP(=S)(OCC)SC(CCl)N1C(=O)c2ccccc2C1=O,-6.340
6,Sorbitol,OCC(O)C(O)C(O)C(O)CO,OCC(O)C(O)C(O)C(O)CO,1.090
7,phenobarbital,CCC1(C(=O)NC(=O)NC1=O)c2ccccc2,CCC1(c2ccccc2)C(=O)NC(=O)NC1=O,-2.322
8,DDD,ClC(Cl)C(c1ccc(Cl)cc1)c2ccc(Cl)cc2,Clc1ccc(C(c2ccc(Cl)cc2)C(Cl)Cl)cc1,-7.200
9,5-Ethyl-5-phenylbarbital,O=C1NC(=O)NC(=O)C1(CC)c1ccccc1,CCC1(c2ccccc2)C(=O)NC(=O)NC1=O,-2.322
10,Dialifos,CCOP(=S)(OCC)SC(CCl)N2C(=O)c1ccccc1C2=O,CCOP(=S)(OCC)SC(CCl)N1C(=O)c2ccccc2C1=O,-6.340
11,2-Bromonapthalene,Brc1ccc2ccccc2c1,Brc1ccc2ccccc2c1,-4.400
12,Androsterone,CC12CCC(O)CC1CCC3C2CCC4(C)C3CCC4=O,CC12CCC3C(CCC4CC(O)CCC43C)C1CCC2=O,-4.402
13,Guaiacol,COc1ccccc1O,COc1ccccc1O,-1.960
14,probarbital,CCC1(C(C)C)C(=O)NC(=O)NC1=O,CCC1(C(C)C)C(=O)NC(=O)NC1=O,-2.210
15,Metronidazole,Cc1ncc(N(=O)=O)n1CCO,Cc1ncc([N+](=O)[O-])n1CCO,-1.220
16,5-Ethyl-5-(3-methylbutyl)barbital,O=C1NC(=O)NC(=O)C1(CC)CCC(C)C,CCC1(CCC(C)C)C(=O)NC(=O)NC1=O,-2.658
17,Metranidazole,Cc1ncc(N(=O)=O)n1CCO,Cc1ncc([N+](=O)[O-])n1CCO,-1.260
18,5-Ethyl-5-isopropylbarbituric acid,O=C1NC(=O)NC(=O)C1(CC)C(C)C,CCC1(C(C)C)C(=O)NC(=O)NC1=O,-2.148
19,"1,8-Cineole",CC12CCC(CC1)C(C)(C)O2,CC12CCC(CC1)C(C)(C)O2,-1.740
20,"P,P'-DDD",ClC(Cl)C(c1ccc(Cl)cc1)c2ccc(Cl)cc2,Clc1ccc(C(c2ccc(Cl)cc2)C(Cl)Cl)cc1,-7.200
21,o-Methoxyphenol,COc1ccccc1O,COc1ccccc1O,-1.960

In [5]:
duplicates_label = pd.read_csv('/Data/temuge/cov19/drugdevelopment_pp/molecular_admet/reports/duplicate_label_summary.csv')
duplicates_label

,canonical_smiles,count,mean,std,minimum,maximum,range
0,OCC(O)C(O)C(O)C(O)CO,2,0.575,0.728320,0.060,1.090,1.030
1,CC12CCC3C(CCC4CC(O)CCC43C)C1CCC2=O,2,-4.281,0.171120,-4.402,-4.160,0.242
2,CCC1(CCC(C)C)C(=O)NC(=O)NC1=O,2,-2.563,0.134350,-2.658,-2.468,0.190
3,CC12CCC(CC1)C(C)(C)O2,2,-1.690,0.070711,-1.740,-1.640,0.100
4,CCC1(C(C)C)C(=O)NC(=O)NC1=O,2,-2.179,0.043841,-2.210,-2.148,0.062
5,Cc1ncc([N+](=O)[O-])n1CCO,2,-1.240,0.028284,-1.260,-1.220,0.040
6,Brc1ccc2ccccc2c1,2,-4.400,0.000000,-4.400,-4.400,0.000
7,CCOP(=S)(OCC)SC(CCl)N1C(=O)c2ccccc2C1=O,2,-6.340,0.000000,-6.340,-6.340,0.000
8,CCC1(c2ccccc2)C(=O)NC(=O)NC1=O,2,-2.322,0.000000,-2.322,-2.322,0.000
9,COc1ccccc1O,2,-1.960,0.000000,-1.960,-1.960,0.000
10,Clc1ccc(C(c2ccc(Cl)cc2)C(Cl)Cl)cc1,2,-7.200,0.000000,-7.200,-7.200,0.000

In [7]:
delanay[delanay['Compound ID'] == 'Amobarbital'].smiles

147    CCC1(CCC(C)C)C(=O)NC(=O)NC1=O
Name: smiles, dtype: object

In [8]:
curlog = pd.read_csv('/Data/temuge/cov19/drugdevelopment_pp/molecular_admet/reports/curation_log.csv')
curlog

,canonical_smiles,n_source_records,label_min,label_max,label_range,action
0,N#CC(OC1OC(COC2OC(CO)C(O)C(O)C2O)C(O)C(O)C1O)c...,1,-0.770,-0.770,0.0,keep_unique
1,Cc1occc1C(=O)Nc1ccccc1,1,-3.300,-3.300,0.0,keep_unique
2,CC(C)=CCCC(C)=CC=O,1,-2.060,-2.060,0.0,keep_unique
3,c1ccc2c(c1)ccc1c2ccc2c3ccccc3ccc21,1,-7.870,-7.870,0.0,keep_unique
4,c1ccsc1,1,-1.330,-1.330,0.0,keep_unique
...,...,...,...,...,...,...
1112,FC(F)(F)C(Cl)Br,1,-1.710,-1.710,0.0,keep_unique
1113,CNC(=O)ON=C(SC)C(=O)N(C)C,1,0.106,0.106,0.0,keep_unique
1114,CCSCCSP(=S)(OC)OC,1,-3.091,-3.091,0.0,keep_unique
1115,CCC(C)C,1,-3.180,-3.180,0.0,keep_unique
1116,COP(=O)(OC)OC(=CCl)c1cc(Cl)c(Cl)cc1Cl,1,-4.522,-4.522,0.0,keep_unique

In [9]:
conf_dup = pd.read_csv('/Data/temuge/cov19/drugdevelopment_pp/molecular_admet/reports/conflicting_duplicates.csv')
conf_dup

,compound_id,smiles,canonical_smiles,measured_logS,group_label_min,group_label_max,group_label_range
0,mannitol,OCC(O)C(O)C(O)C(O)CO,OCC(O)C(O)C(O)C(O)CO,0.06,0.06,1.09,1.03
1,Sorbitol,OCC(O)C(O)C(O)C(O)CO,OCC(O)C(O)C(O)C(O)CO,1.09,0.06,1.09,1.03

In [11]:
delanay.smiles.nunique()

1128

In [18]:
delanay[delanay['Compound ID'].isin(['mannitol', 'Sorbitol'])]

,Compound ID,ESOL predicted log solubility in mols per litre,Minimum Degree,Molecular Weight,Number of H-Bond Donors,Number of Rings,Number of Rotatable Bonds,Polar Surface Area,measured log solubility in mols per litre,smiles
233,mannitol,0.647,1,182.172,6,0,5,121.38,0.06,OCC(O)C(O)C(O)C(O)CO
276,Sorbitol,0.647,1,182.172,6,0,5,121.38,1.09,OCC(O)C(O)C(O)C(O)CO

In [19]:
moses = pd.read_csv('/Data/temuge/cov19/drugdevelopment_pp/molecular_admet/data/generation/raw/moses_train.csv')
moses

                                           SMILES  SPLIT
0          CCCS(=O)c1ccc2[nH]c(=NC(=O)OC)[nH]c2c1  train
1            CC(C)(C)C(=O)C(Oc1ccc(Cl)cc1)n1ccnc1  train
2             Cc1c(Cl)cccc1Nc1ncccc1C(=O)OCC(O)CO  train
3                Cn1cnc2c1c(=O)n(CC(O)CO)c(=O)n2C  train
4                  CC1Oc2ccc(Cl)cc2N(CC(O)CO)C1=O  train
...                                           ...    ...
1584658                      N#Cc1c(Br)cnc(N)c1Br  train
1584659        COC(=O)c1cc(CNC(=O)OC(C)(C)C)ccc1C  train
1584660                    NC(=O)c1ccc2ccccc2c1Br  train
1584661  CC(=O)Nc1cccc(-c2nc3cc(C)ccc3[nH]c2=O)c1  train
1584662   CC(NC(=O)OC(C)(C)C)c1nc(CO)nn1Cc1ccccc1  train

[1584663 rows x 2 columns]

In [20]:
vae_genall = pd.read_csv('/Data/temuge/cov19/drugdevelopment_pp/molecular_admet/data/generation/processed/vae_generated_all.csv')
vae_genall

,generated_smiles,valid,canonical_smiles
0,Cc1noc(C)c1CC(=O)NCc1cccc(OC)c1OC,True,COc1cccc(CNC(=O)Cc2c(C)noc2C)c1OC
1,COC(=O)C1CCCN(C(=O)CN(C)c2ccccc2F)C1,True,COC(=O)C1CCCN(C(=O)CN(C)c2ccccc2F)C1
2,Cc1cccc(-c2nc3[nH]c4c(cn3n2)C(C)COCC3)c1,False,NaN
3,O=C(Cn1ncc(C(=O)NC2CCCCC2)c1)NCC1CCC1,True,O=C(Cn1cc(C(=O)NC2CCCCC2)cn1)NCC1CCC1
4,O=C(Nc1ccccc1Cl)c1ncn(-c2ccccc2)n1,True,O=C(Nc1ccccc1Cl)c1ncn(-c2ccccc2)n1
...,...,...,...
9995,Cc1cc(C)c2c(n1)CCN(C(=O)c1ccsc1)CC2,True,Cc1cc(C)c2c(n1)CCN(C(=O)c1ccsc1)CC2
9996,COC(=O)C(C)(C)NCC(=O)Nc1ccccc1C(F)(F)F,True,COC(=O)C(C)(C)NCC(=O)Nc1ccccc1C(F)(F)F
9997,CC(Cc1ccccc1)NC(=O)c1cnn(-c2ccccc2)c1,True,CC(Cc1ccccc1)NC(=O)c1cnn(-c2ccccc2)c1
9998,CC(C)(C)OC(=O)NCC(O)c1ccccc1C#N,True,CC(C)(C)OC(=O)NCC(O)c1ccccc1C#N
9999,CNC(=O)c1ccc(OCC(=O)Nc2c(F)cccc2F)cc1,True,CNC(=O)c1ccc(OCC(=O)Nc2c(F)cccc2F)cc1

In [21]:
vae_gen_scr = pd.read_csv('/Data/temuge/cov19/drugdevelopment_pp/molecular_admet/data/generation/processed/vae_generated_screened.csv')
vae_gen_scr

,generated_smiles,valid,canonical_smiles,novel_vs_training,desc_mol_weight,desc_logp,desc_tpsa,desc_hbd,desc_hba,desc_rotatable_bonds,...,lipinski_logp_violation,lipinski_hbd_violation,lipinski_hba_violation,lipinski_violations,lipinski_compliant,predicted_logS,predicted_solubility_mol_L,n_descriptors_outside_esol_range,inside_esol_descriptor_range,basic_candidate
0,Cc1noc(C)c1CC(=O)NCc1cccc(OC)c1OC,True,COc1cccc(CNC(=O)Cc2c(C)noc2C)c1OC,True,304.346,2.16754,73.59,1,5,6,...,False,False,False,0,True,-3.828128,0.000149,0,True,True
1,COC(=O)C1CCCN(C(=O)CN(C)c2ccccc2F)C1,True,COC(=O)C1CCCN(C(=O)CN(C)c2ccccc2F)C1,True,308.353,1.67350,49.85,0,4,4,...,False,False,False,0,True,-3.121604,0.000756,0,True,True
2,O=C(Cn1ncc(C(=O)NC2CCCCC2)c1)NCC1CCC1,True,O=C(Cn1cc(C(=O)NC2CCCCC2)cn1)NCC1CCC1,True,318.421,1.86190,76.02,2,3,6,...,False,False,False,0,True,-4.022882,0.000095,0,True,True
3,O=C(Nc1ccccc1Cl)c1ncn(-c2ccccc2)n1,True,O=C(Nc1ccccc1Cl)c1ncn(-c2ccccc2)n1,True,298.733,3.17300,59.81,1,3,3,...,False,False,False,0,True,-4.488664,0.000032,0,True,True
4,Cc1ccsc1C(=O)Nc1oc(Cn2cccn2)cc1C,True,Cc1cc(Cn2cccn2)oc1NC(=O)c1sccc1C,True,301.371,3.45504,60.06,1,4,4,...,False,False,False,0,True,-4.439463,0.000036,0,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8784,Cc1cc(C)c2c(n1)CCN(C(=O)c1ccsc1)CC2,True,Cc1cc(C)c2c(n1)CCN(C(=O)c1ccsc1)CC2,True,286.400,3.00094,33.20,0,3,1,...,False,False,False,0,True,-3.981622,0.000104,0,True,True
8785,COC(=O)C(C)(C)NCC(=O)Nc1ccccc1C(F)(F)F,True,COC(=O)C(C)(C)NCC(=O)Nc1ccccc1C(F)(F)F,True,318.295,2.18510,67.43,2,4,5,...,False,False,False,0,True,-3.789288,0.000162,0,True,True
8786,CC(Cc1ccccc1)NC(=O)c1cnn(-c2ccccc2)c1,True,CC(Cc1ccccc1)NC(=O)c1cnn(-c2ccccc2)c1,True,305.381,3.23330,46.92,1,2,5,...,False,False,False,0,True,-4.058883,0.000087,0,True,True
8787,CC(C)(C)OC(=O)NCC(O)c1ccccc1C#N,True,CC(C)(C)OC(=O)NCC(O)c1ccccc1C#N,True,262.309,2.11638,82.35,2,4,3,...,False,False,False,0,True,-2.943958,0.001138,0,True,True
8788,CNC(=O)c1ccc(OCC(=O)Nc2c(F)cccc2F)cc1,True,CNC(=O)c1ccc(OCC(=O)Nc2c(F)cccc2F)cc1,True,320.295,2.34190,67.43,2,3,5,...,False,False,False,0,True,-3.927700,0.000118,0,True,True

In [26]:
pd.DataFrame([{'a': 1, 'b':2, 'c':3}, {'a': 89, 'b':67, 'c':34}, {'a': 123, 'b':456, 'c':789}])

     a    b    c
0    1    2    3
1   89   67   34
2  123  456  789

In [27]:
pd.DataFrame({'a': [1,89, 123], 'b':[2, 67, 456], 'c':[3, 34, 789]})

     a    b    c
0    1    2    3
1   89   67   34
2  123  456  789